### ISSUE TITLE
Magic numbers for image preprocessing

### ISSUE THREAD

**Issue by wenfenglin** [scaelles/OSVOS-TensorFlow#19]
@scaelles Thanks for sharing this project.

In the function preprocess_img() from osvos.py, where do the mean values (104.00699, 116.66877, 122.67892) come from? I saw those numbers in a lot of projects, but no one has explained how they are calculated.

**Comment by kmaninis** [comment]
Hi, you are right! There is some explanation behind those numbers :)
They are the mean color values of BSDS500 dataset, used for an old experiment that we were doing.

Since changing these values did not contribute anything to our tasks, we kept them as they are.
For the record, they are taken from [here](https://github.com/s9xie/hed/blob/master/examples/hed/HED-tutorial.ipynb).

**Comment by wenfenglin** [comment]
Thanks for your prompt response! It is really helpful.
