### ISSUE TITLE
For video

### ISSUE THREAD

**Issue by Raj7kumar7** [scaelles/OSVOS-TensorFlow#22]
Hello
Nice work.If we need to do segmentation for a video what should i do?
Kindly help.

**Comment by scaelles** [comment]
Hello,
Once you have a video sequence, you have to extract its frames. Then, you have to annotate manually the segmentation mask of the object that you want to segment in the first frame of the video. After that, you can use our method to perform the segmentation in all the other frames of the video. In order to extract the frames and then to create a video again with the segmentation results, I would recommend you using `ffmpeg`. Let us know if you have any further question.
